---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: localhost
    managed: false
    module: ansible.builtin.raw
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: "/tmp"
  inventory:
    host_vars:
      localhost:
        ansible_python_interpreter: "${MOLECULE_PYTHON_INTERPRETER:-python3}"
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
    - converge
    - verify
