---
name: Feature Request
description: Suggest a new feature or enhancement
labels: [enhancement, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe what you'd like.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the use case?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work? Include example playbook snippets if possible.
      render: yaml
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      options:
        - New module
        - New entity type support
        - Module enhancement
        - Documentation improvement
        - Testing improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or references.
